#!/usr/bin/env node
# Don't redirect static files and assets
/favicon.ico 200
/favicon.svg 200
/icon.png 200
/icon-192x192.png 200
/icon-512x512.png 200
/logo.png 200
/logo.svg 200
/apple-touch-icon.png 200
/opengraph.jpg 200
/aadhaar_mask_mockup.png 200
/document_processing_mockup.png 200
/photo_resize_mockup.png 200
/*.json 200
/*.txt 200
/*.xml 200
/*.css 200
/*.js 200
/*.png 200
/*.svg 200
/*.jpg 200
/*.jpeg 200
/*.gif 200
/*.webp 200
/*.woff 200
/*.woff2 200
/*.ttf 200
/*.otf 200
/*.eot 200

# SPA fallback - rewrite all non-matching routes to index.html
/* /index.html 200
