export interface ThemeConfig {
  id: string;
  name: string;
  occasion: string;
  description: string;
  colorFrom: string; // Hex color for swatch start
  colorTo: string; // Hex color for swatch end
  gradient: string; // CSS style gradient
  icon: string; // string identifier for icon mapping
  particles: {
    type: "marigold" | "colorSplashes" | "diyas" | "alpana" | "snow" | "sparkles" | "caps" | "tricolorStars" | "notes" | "embers" | "digital" | "none";
    density: number;
    speed: number;
  };
}

export const THEME_REGISTRY: Record<string, ThemeConfig> = {
  none: {
    id: "none",
    name: "Standard Dark",
    occasion: "Default System UI",
    description: "The sleek, modern file-nova dark blue theme with subtle blue highlights.",
    colorFrom: "#3b82f6",
    colorTo: "#1e1b4b",
    gradient: "linear-gradient(135deg, #090d16 0%, #111827 100%)",
    icon: "default",
    particles: { type: "none", density: 0, speed: 0 },
  },
  durgaPuja: {
    id: "durgaPuja",
    name: "Durga Puja",
    occasion: "Autumn Festival (West Bengal)",
    description: "Deep crimson, vermillion, and marigold amber. Floating petals and Kash phool.",
    colorFrom: "#dc2626",
    colorTo: "#fbbf24",
    gradient: "linear-gradient(135deg, #160a0a 0%, #241111 100%)",
    icon: "puja",
    particles: { type: "marigold", density: 30, speed: 1.1 },
  },
  holi: {
    id: "holi",
    name: "Holi / Dol Jatra",
    occasion: "Spring Festival of Colors",
    description: "Vibrant splashes of gulal pink, turquoise, and violet colors.",
    colorFrom: "#ec4899",
    colorTo: "#06b6d4",
    gradient: "linear-gradient(135deg, #080711 0%, #151226 100%)",
    icon: "holi",
    particles: { type: "colorSplashes", density: 40, speed: 1.4 },
  },
  diwali: {
    id: "diwali",
    name: "Diwali & Kali Puja",
    occasion: "Festival of Lights",
    description: "Deep plum purple and glowing diya gold with interactive sparkles.",
    colorFrom: "#fbbf24",
    colorTo: "#7c3aed",
    gradient: "linear-gradient(135deg, #0c0617 0%, #1b0f2e 100%)",
    icon: "diwali",
    particles: { type: "diyas", density: 25, speed: 0.8 },
  },
  poilaBaisakh: {
    id: "poilaBaisakh",
    name: "Poila Baisakh",
    occasion: "Bengali New Year",
    description: "Traditional terracotta red and white alpana rice-paste designs.",
    colorFrom: "#ea580c",
    colorTo: "#fffbeb",
    gradient: "linear-gradient(135deg, #150d0a 0%, #241611 100%)",
    icon: "alpana",
    particles: { type: "alpana", density: 20, speed: 1.0 },
  },
  saraswatiPuja: {
    id: "saraswatiPuja",
    name: "Saraswati Puja",
    occasion: "Basant Panchami",
    description: "Basanti yellow, sitars, and marigolds representing knowledge and art.",
    colorFrom: "#eab308",
    colorTo: "#fffbeb",
    gradient: "linear-gradient(135deg, #0f0d06 0%, #1d180c 100%)",
    icon: "sitar",
    particles: { type: "notes", density: 30, speed: 1.1 },
  },
  eid: {
    id: "eid",
    name: "Eid Mubarak",
    occasion: "Islamic Eid Festival",
    description: "Emerald green backgrounds with glowing crescent moons and floating stars.",
    colorFrom: "#fbbf24",
    colorTo: "#059669",
    gradient: "linear-gradient(135deg, #03170d 0%, #092c1a 100%)",
    icon: "eid",
    particles: { type: "sparkles", density: 25, speed: 0.8 },
  },
  christmas: {
    id: "christmas",
    name: "Christmas Time",
    occasion: "Winter Holidays",
    description: "Nordic pine forest green, cherry red, and peaceful falling snow.",
    colorFrom: "#e11d48",
    colorTo: "#10b981",
    gradient: "linear-gradient(135deg, #051410 0%, #0c261e 100%)",
    icon: "christmas",
    particles: { type: "snow", density: 45, speed: 1.3 },
  },
  newYear: {
    id: "newYear",
    name: "New Year Celebration",
    occasion: "New Year's Eve / Day",
    description: "Elegant void black with champagne gold sparkles and firework bursts.",
    colorFrom: "#ca8a04",
    colorTo: "#1e293b",
    gradient: "linear-gradient(135deg, #040406 0%, #0e0e13 100%)",
    icon: "newyear",
    particles: { type: "sparkles", density: 40, speed: 1.2 },
  },
  scholarship: {
    id: "scholarship",
    name: "Admission Season",
    occasion: "College Admissions & Scholarships",
    description: "Academic navy blue and gold with floating graduation caps and diplomas.",
    colorFrom: "#fbbf24",
    colorTo: "#1d4ed8",
    gradient: "linear-gradient(135deg, #040b19 0%, #0b1528 100%)",
    icon: "academic",
    particles: { type: "caps", density: 22, speed: 0.9 },
  },
  tricolor: {
    id: "tricolor",
    name: "Indian Tricolor",
    occasion: "Independence & Republic Day",
    description: "Saffron, white, and green gradients with rotating Ashok Chakras.",
    colorFrom: "#f97316",
    colorTo: "#22c55e",
    gradient: "linear-gradient(135deg, #08100b 0%, #121e16 100%)",
    icon: "flag",
    particles: { type: "tricolorStars", density: 30, speed: 1.0 },
  },
  rabindraJayanti: {
    id: "rabindraJayanti",
    name: "Rabindra Jayanti",
    occasion: "Tagore Birth Anniversary",
    description: "Literary terracotta and parchment paper yellow with musical elements.",
    colorFrom: "#b45309",
    colorTo: "#fdf6e2",
    gradient: "linear-gradient(135deg, #110b09 0%, #1f1411 100%)",
    icon: "music",
    particles: { type: "notes", density: 25, speed: 0.9 },
  },
  warm: {
    id: "warm",
    name: "Festival Warmth",
    occasion: "General Celebration",
    description: "Radiant sunset red-orange gradients with rising heat ember particles.",
    colorFrom: "#f43f5e",
    colorTo: "#e11d48",
    gradient: "linear-gradient(135deg, #110707 0%, #1a0d0d 100%)",
    icon: "warm",
    particles: { type: "embers", density: 35, speed: 1.2 },
  },
  cool: {
    id: "cool",
    name: "Digital Cool",
    occasion: "Modern Tech Aesthetic",
    description: "Electric cyber cyan and indigo with falling technical grid nodes.",
    colorFrom: "#06b6d4",
    colorTo: "#3b82f6",
    gradient: "linear-gradient(135deg, #030712 0%, #0b0f19 100%)",
    icon: "cool",
    particles: { type: "digital", density: 30, speed: 1.3 },
  },
};
